### matrix application using Numpy

### NumPy
 numpy is a (numeriacal python) is the foundational library for scientific computing in python 
 * a powerful n-dimensinonal array object


In [15]:
import numpy as np

In [18]:
# zero dimensional Array it is no particular direction
arr = np.array(42)
print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [ ]:
# single directional array  (by using list)
arr = np.array([11,22,33])
print(arr)
print(type(arr))

[11 22 33]
<class 'numpy.ndarray'>


In [22]:
# single directional array (by using tuple)
arr = np.array((11,22,33))
print(arr)
print(type(arr))

[11 22 33]
<class 'numpy.ndarray'>


In [29]:
# 2 dimensional array(3x3 matrix)

arr = np.array([[1,2],[3,4]])

print(arr)
print(type(arr))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [36]:
## special arrays
zeros = np.zeros((3,3))
print("Zeroes Matrix : \n",zeros)
ones = np.ones((3,3))
print("Ones Matrix : \n",ones)
eye = np.eye(3)
print("Identity matrix : \n",eye)
rand = np.random.randint(1,10,size=(3,3))
print("Random Matrix : \n",rand)

Zeroes Matrix : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix : 
 [[6 1 8]
 [4 7 3]
 [5 5 1]]


In [46]:
# arange and linespace

arr_range = np.arange(0,20,2)   # start from 2 and end at 20 with differnce 2
print("matrix in a range : ",arr_range)

arr_lin = np.linspace(0,1,5)  # it will give number(5) of equal distrbution in given range 
print("Range is equally distrubuted : ",arr_lin)

matrix in a range :  [ 0  2  4  6  8 10 12 14 16 18]
Range is equally distrubuted :  [0.   0.25 0.5  0.75 1.  ]
